apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gw-vsvc
spec:
  gateways:
  - gw-gateway
  hosts:
  - "test.local"
  http:
  - name: primary
    route:
    - destination:
        host: bluesvc
      weight: 0
    - destination:
        host: greensvc
      weight: 100